server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: admin
    password: kojan123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
  main:
    web-application-type: servlet